In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
house = pd.read_excel('cr2.xlsx', sheet_name='house',header=None)
 

In [3]:
tube = pd.read_excel('cr2.xlsx', sheet_name='tube',header=None)

In [4]:
tube.columns = ['lat', 'long','name']

In [5]:
house.columns = ['price','lat', 'long']

In [6]:
latMAX = 51.7
latMIN = 51.3
longMAX = 0.3
longMIN = -0.6

In [7]:
r= house.shape[0]
location = []


for i in range(r):
    lat = house['lat'][i]
    long = house['long'][i]
    if lat>=latMIN and lat<=latMAX and long>=longMIN and long<=longMAX:
        location.append([lat,long,house['price'][i]])
        #price.append(house['price'][i])
        
        

In [8]:
rr = tube.shape[0]
location_tube = []
name = []

for i in range(rr):
    lat = house['lat'][i]
    long = house['long'][i]
    if lat>=latMIN and lat<=latMAX and long>=longMIN and long<=longMAX:
        location_tube.append([lat,long])
        name.append(tube['name'][i])

In [9]:
location=np.array(location)
#price=np.array(price)
location_tube=np.array(location_tube)
name=np.array(name)


In [156]:
from random import seed
from random import randrange

# Split a dataset into k folds
def cross_validation_split(dataset, folds=3):
    dataset_split = []
    dataset_copy = dataset
    fold_size = int(len(dataset) / folds)
    for i in range(folds):
        fold =[]
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy[index,:])
            dataset_copy=np.delete(dataset_copy, index,0)
        dataset_split.append(fold)
    return dataset_split

In [158]:
folds = cross_validation_split(location)


In [159]:
folds

[[array([ 5.14642471e+01, -1.84009600e-01,  1.62500000e+03]),
  array([ 5.1497838e+01, -2.2255160e-01,  1.1920000e+03]),
  array([ 5.14630598e+01, -1.09821300e-01,  1.56000000e+03]),
  array([ 5.14341868e+01, -1.30953000e-01,  1.15000000e+03]),
  array([ 5.14391197e+01, -1.71067200e-01,  1.40800000e+03]),
  array([ 5.14943529e+01, -8.30243000e-02,  1.12700000e+03]),
  array([ 5.15063899e+01, -4.24450000e-03,  1.51700000e+03]),
  array([ 5.15165268e+01, -1.96465000e-02,  1.04000000e+03]),
  array([ 5.14920651e+01, -1.78356900e-01,  1.73300000e+03]),
  array([ 5.14547513e+01, -3.24508000e-02,  8.25000000e+02]),
  array([ 5.15681951e+01, -9.62695000e-02,  1.30000000e+03]),
  array([ 5.1556214e+01, -2.1357500e-01,  1.0620000e+03]),
  array([ 5.1499451e+01, -6.1503900e-02,  8.0200000e+02]),
  array([ 5.14565622e+01, -2.02826000e-02,  8.00000000e+02]),
  array([ 5.15243312e+01, -1.61401500e-01,  1.73300000e+03]),
  array([ 5.15617479e+01, -1.47194900e-01,  1.25000000e+03]),
  array([ 5.15174

In [10]:
from mpl_toolkits import mplot3d
%matplotlib notebook

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(location_tube[:,0], location_tube[:,1],color='g')
ax.set_xlabel('lat')
ax.set_ylabel('long')

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(location[:,0], location[:,1],location[:,2],c='r')

ax.scatter3D(location_tube[:,0], location_tube[:,1],color='g')
ax.set_xlabel('lat')
ax.set_ylabel('long')




In [16]:
muMin = np.min(london)
muMax = np.max(london)
NumBasisFnsx = 7
NumBasisFnsy = 7
mu = np.zeros((NumBasisFnsx*NumBasisFnsy, 2))
s = (muMax - muMin)/(NumBasisFnsx)
for ii in range(NumBasisFnsx):
        for jj in range(NumBasisFnsy):
                mu[(ii)*NumBasisFnsx+jj, 0] = muMin[0] + (ii-1)*(muMax[0]-muMin[0])/(NumBasisFnsx-1)
                mu[(ii)*NumBasisFnsy+jj, 1] = muMin[1] + (jj-1)*(muMax[1]-muMin[1])/(NumBasisFnsy-1)

In [132]:
mu.shape

(49, 2)

In [18]:
s[0]

0.05549707142857179

In [129]:
from tqdm import tqdm

def basis_unigrid(data, mu):
    numBasisFncs = len(mu)+1
    Thetas = np.zeros((len(data), numBasisFncs))
    for ii in tqdm(range(len(data))):
        for jj in range(numBasisFncs):
            if jj == 0:
                Thetas[ii,jj] = 1
            else:
                Thetas[ii,jj] = np.exp( -( (((data['lat'][ii]-mu[jj-1,0])**2)/(2*(s[0]**2))) + \
                                       (((data['long'][ii]-mu[jj-1,1])**2)/(2*(s[1]**2))) ) )
    return Thetas

In [157]:
from random import seed
from random import randrange

# Split a dataset into k folds
def cross_validation_split(dataset, folds=3):
    dataset_split = []
    dataset_copy = dataset
    fold_size = int(len(dataset) / folds)
    for i in range(folds):
        fold =[]
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy[index,:])
            dataset_copy=np.delete(dataset_copy, index,0)
        dataset_split.append(fold)
    return dataset_split

In [160]:
london

lat      long   price
0      51.506954 -0.019372   563.0
1      51.527400 -0.189900  1473.0
2      51.512018 -0.199160  3250.0
3      51.526153 -0.253267  1105.0
4      51.564530 -0.305760   900.0
5      51.454484 -0.340631  1075.0
6      51.521841 -0.482566   800.0
7      51.434876 -0.133334   850.0
8      51.596043 -0.204212  1625.0
9      51.496423 -0.194583  2275.0
10     51.507514 -0.021136  2947.0
11     51.484064  0.078141   700.0
12     51.456562 -0.020283   800.0
13     51.405637 -0.093263   699.0
14     51.405637 -0.093263   699.0
15     51.399043 -0.082860   750.0
16     51.499974 -0.213864  1473.0
17     51.464863 -0.265296  1127.0
18     51.457212 -0.005853  1096.0
19     51.513304 -0.149788  1993.0
20     51.426799 -0.331342  1300.0
21     51.634296 -0.048104   750.0
22     51.618839 -0.055654   850.0
23     51.525135 -0.188377  1430.0
24     51.434303 -0.178715   953.0
25     51.443351 -0.146927  1300.0
26     51.538123 -0.207027  1170.0
27     51.538271 -0.211902  1647.0
28     51.629572 -0.125290   950.0
29     51.615271 -0.062190   550.0
...          ...       ...     ...
14526  51.542336 -0.163020  1842.0
14527  51.527125 -0.063767  1842.0
14528  51.546836 -0.220171  1430.0
14529  51.437838 -0.014025   725.0
14530  51.453266  0.014044   650.0
14531  51.434303 -0.178715  1096.0
14532  51.562880 -0.013606   910.0
14533  51.593095 -0.172343  1062.0
14534  51.417869 -0.203676  1000.0
14535  51.644679 -0.040188   800.0
14536  51.407741 -0.026243   800.0
14537  51.610057 -0.147128   953.0
14538  51.494280 -0.034962  1408.0
14539  51.494015 -0.149441  2167.0
14540  51.505988 -0.214009  1842.0
14541  51.462206 -0.132920  1647.0
14542  51.462206 -0.132920  1647.0
14543  51.462206 -0.132920  1647.0
14544  51.468813 -0.205396  1517.0
14545  51.462148 -0.140181  1603.0
14546  51.512489 -0.068441  1603.0
14547  51.511174 -0.098435  1712.0
14548  51.514947 -0.275315  1250.0
14549  51.518308 -0.193860  1517.0
14550  51.494413 -0.177454  1582.0
14551  51.496663 -0.179187  2817.0
14552  51.511737 -0.034524  1733.0
14553  51.519603 -0.121823  2058.0
14554  51.539809 -0.199431  1408.0
14555  51.503944 -0.241046  1517.0

[14556 rows x 3 columns]

In [164]:
london[['lat','long']].values

array([[ 5.15069539e+01, -1.93718000e-02],
       [ 5.15274000e+01, -1.89900000e-01],
       [ 5.15120178e+01, -1.99160200e-01],
       ...,
       [ 5.15196027e+01, -1.21822800e-01],
       [ 5.15398093e+01, -1.99431400e-01],
       [ 5.15039438e+01, -2.41045600e-01]])

In [188]:
from sklearn.model_selection import StratifiedKFold

kfold = StratifiedKFold(n_splits=5,random_state=1).split(london[['lat','long']].values, london['price'].values)


In [189]:
for k, (train, test) in enumerate(kfold):
    print(london.iloc[test])

/Users/yuekang/anaconda3/lib/python3.5/site-packages/sklearn/model_selection/_split.py:626: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


             lat      long    price
0      51.506954 -0.019372    563.0
1      51.527400 -0.189900   1473.0
2      51.512018 -0.199160   3250.0
3      51.526153 -0.253267   1105.0
4      51.564530 -0.305760    900.0
5      51.454484 -0.340631   1075.0
6      51.521841 -0.482566    800.0
7      51.434876 -0.133334    850.0
8      51.596043 -0.204212   1625.0
9      51.496423 -0.194583   2275.0
10     51.507514 -0.021136   2947.0
11     51.484064  0.078141    700.0
12     51.456562 -0.020283    800.0
13     51.405637 -0.093263    699.0
15     51.399043 -0.082860    750.0
16     51.499974 -0.213864   1473.0
17     51.464863 -0.265296   1127.0
18     51.457212 -0.005853   1096.0
19     51.513304 -0.149788   1993.0
20     51.426799 -0.331342   1300.0
21     51.634296 -0.048104    750.0
22     51.618839 -0.055654    850.0
23     51.525135 -0.188377   1430.0
24     51.434303 -0.178715    953.0
25     51.443351 -0.146927   1300.0
26     51.538123 -0.207027   1170.0
27     51.538271 -0.211902  

In [130]:
theta = basis_unigrid(london,mu)

100%|██████████| 14556/14556 [01:02<00:00, 234.73it/s]


In [141]:
W = np.linalg.pinv(theta)
W = np.dot(W,london['price'])
W.shape

(50,)

In [92]:
cov = np.cov(london['lat'],london['long'])

In [100]:
from numpy.linalg import inv

def multivariable_guassian(x,mu,cov):
    f = np.exp(-1/2*np.dot(np.dot((x- new_mu).T,inv(cov)),(x- new_mu)))
    return f

In [99]:
lat_mu,long_mu,_ = london.mean(0)
new_mu= np.array([lat_mu,long_mu])
new_mu=new_mu.reshape(2,1)


x=np.array([london['lat'][1],london['long'][1]]).reshape(2,1)
np.dot(np.dot((x- new_mu).T,inv(cov)),(x- new_mu))
#np.exp(-1/2*(x-new_mu).T*inv(cov)*(x-new_mu))

array([[0.47638404]])

In [117]:
london['lat'].values[1]
f= []

for i, j in zip(london['lat'].values,london['long'].values):
    x = np.array([i,j]) .reshape(2,1)
    a = multivariable_guassian(x,new_mu,cov)
    f.append(a)
    
    


In [143]:
def testRegressor(test_Input, param):
    mu = param[0]
    s = param[1]
    numBasisFncs = length(mu)+1
    Thetas = zeros(length(test_Input), numBasisFncs)
    for ii in tqdm(range(len(test_Input))):
        for jj in range(numBasisFncs):
            if jj == 0:
                Thetas[ii,jj] = 1
            else:
                Thetas[ii,jj] = np.exp( -( (((data['lat'][ii]-mu[jj-1,0])**2)/(2*(s[0]**2))) + \
                                       (((data['long'][ii]-mu[jj-1,1])**2)/(2*(s[1]**2))) ) )
    prediction = Thetas * param[2]
    return prediction